apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-website
  namespace: main
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      run: cn-website
  replicas: 3
  template:
    metadata:
      labels:
        run: cn-website
    spec:
      containers:
      - name: cn-website
        image: jonsy13/cn-website:main-3e82ac65c95238c4431147f6c37cf04dbbf9e77a
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
