---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-website
  namespace: main
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      run: cn-website
  replicas: 3
  template:
    metadata:
      labels:
        run: cn-website
    spec:
      containers:
      - name: cn-website
        image: jonsy13/cn-website:main-c0eef110e02bd1770ca7d0ba337513ca8a352b35
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
