apiVersion: v1
kind: Service
metadata:
  name: cn-website
  namespace: main
  labels:
    run: cn-website
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: cn-website
